Install test,fmt,clippy CI jobs
nordzilla/cargo-doc-gen pull request #8
Opened 2021-04-10 20:56 UTC by connorkuehl

2021-04-10 21:00 UTC, squidboylan approved these changes

2021-04-11 00:59 UTC, nordzilla requested changes

2021-04-11 00:59 UTC, nordzilla commented on .github/workflows/test.yml
> +          command: test
Please add a newline at the end of file.

2021-04-11 00:59 UTC, nordzilla commented on .github/workflows/lint.yml
> +          args: -- -D warnings
Please add a newline at the end of file.

2021-04-11 01:11 UTC, connorkuehl commented
@nordzilla done! PTAL

2021-04-11 01:13 UTC, nordzilla approved these changes
LGTM!

2021-04-11 16:02 UTC, merged